### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test2@test.com",
    "password": "pass"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test2@test.com",
    "password": "pass"
}

### Get currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out
GET http://localhost:3000/auth/signout

### Find one user by ID
GET http://localhost:3000/auth/1

### Find all users by email
GET http://localhost:3000/auth?email=test@test.com

### Update a user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "aaa@test.com"
}

### Delete one user by ID
DELETE http://localhost:3000/auth/1